name: Terraform

on:
  push:
    branches:
      - main
      - featurebranch
      - "feature/**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  TF_VERSION: "1.9.8"

jobs:

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/main'

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Format
        run: terraform fmt -check -recursive parent_module

      - name: Terraform Init
        run: terraform -chdir=parent_module init

      - name: Terraform Validate
        run: terraform -chdir=parent_module validate

      - name: Terraform Plan
        run: terraform -chdir=parent_module plan -out=tfplan


  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Format
        run: terraform fmt -check -recursive parent_module

      - name: Terraform Init
        run: terraform -chdir=parent_module init

      - name: Terraform Validate
        run: terraform -chdir=parent_module validate

      - name: Terraform Plan
        run: terraform -chdir=parent_module plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=parent_module apply -auto-approve tfplan